### ISSUE TITLE
Error with neo4jrb when spatial plugin is added 

### ISSUE THREAD

**Issue by jspenc72** [neo4jrb/neo4jrb_spatial#7]
Added this to my gem file:

``` bash
gem 'neo4jrb_spatial', '1.1.0'
```

Which caused this error:

``` bash
$ rails s
=> Booting WEBrick
=> Rails 4.2.5.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/Users/WREAdmin/.rvm/gems/ruby-head/gems/neo4j-core-6.1.2/lib/neo4j-server/cypher_session.rb:9:in `<module:Server>': superclass mismatch for class CypherSession (TypeError)
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/neo4j-core-6.1.2/lib/neo4j-server/cypher_session.rb:4:in `<module:Neo4j>'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/neo4j-core-6.1.2/lib/neo4j-server/cypher_session.rb:3:in `<top (required)>'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/neo4j-core-6.1.2/lib/neo4j-server.rb:9:in `<top (required)>'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/neo4j-core-6.1.2/lib/neo4j/session.rb:102:in `open'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/neo4j-6.1.7/lib/neo4j/railtie.rb:91:in `block in open_neo4j_session'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/neo4j-6.1.7/lib/neo4j/railtie.rb:104:in `block in wait_for_value'
    from /Users/WREAdmin/.rvm/rubies/ruby-head/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
    from /Users/WREAdmin/.rvm/rubies/ruby-head/lib/ruby/2.2.0/timeout.rb:34:in `block in catch'
    from /Users/WREAdmin/.rvm/rubies/ruby-head/lib/ruby/2.2.0/timeout.rb:34:in `catch'
    from /Users/WREAdmin/.rvm/rubies/ruby-head/lib/ruby/2.2.0/timeout.rb:34:in `catch'
    from /Users/WREAdmin/.rvm/rubies/ruby-head/lib/ruby/2.2.0/timeout.rb:104:in `timeout'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/neo4j-6.1.7/lib/neo4j/railtie.rb:101:in `wait_for_value'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/railties-4.2.5.1/lib/rails/railtie.rb:194:in `public_send'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/railties-4.2.5.1/lib/rails/railtie.rb:194:in `method_missing'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/neo4j-6.1.7/lib/neo4j/railtie.rb:87:in `open_neo4j_session'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/neo4j-6.1.7/lib/neo4j/railtie.rb:144:in `block (2 levels) in <class:Railtie>'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/neo4j-6.1.7/lib/neo4j/railtie.rb:143:in `each'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/neo4j-6.1.7/lib/neo4j/railtie.rb:143:in `block in <class:Railtie>'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/railties-4.2.5.1/lib/rails/initializable.rb:30:in `instance_exec'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/railties-4.2.5.1/lib/rails/initializable.rb:30:in `run'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/railties-4.2.5.1/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /Users/WREAdmin/.rvm/rubies/ruby-head/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
    from /Users/WREAdmin/.rvm/rubies/ruby-head/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
    from /Users/WREAdmin/.rvm/rubies/ruby-head/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
    from /Users/WREAdmin/.rvm/rubies/ruby-head/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
    from /Users/WREAdmin/.rvm/rubies/ruby-head/lib/ruby/2.2.0/tsort.rb:345:in `each'
    from /Users/WREAdmin/.rvm/rubies/ruby-head/lib/ruby/2.2.0/tsort.rb:345:in `call'
    from /Users/WREAdmin/.rvm/rubies/ruby-head/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
    from /Users/WREAdmin/.rvm/rubies/ruby-head/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
    from /Users/WREAdmin/.rvm/rubies/ruby-head/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/railties-4.2.5.1/lib/rails/initializable.rb:54:in `run_initializers'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/railties-4.2.5.1/lib/rails/application.rb:352:in `initialize!'
    from /Users/WREAdmin/Desktop/dev/buyahometogether/webApp/bht-dev/config/environment.rb:5:in `<top (required)>'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
    from /Users/WREAdmin/Desktop/dev/buyahometogether/webApp/bht-dev/config.ru:3:in `block in <main>'
    from /Users/WREAdmin/.rvm/gems/ruby-head@global/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
    from /Users/WREAdmin/.rvm/gems/ruby-head@global/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
    from /Users/WREAdmin/Desktop/dev/buyahometogether/webApp/bht-dev/config.ru:in `new'
    from /Users/WREAdmin/Desktop/dev/buyahometogether/webApp/bht-dev/config.ru:in `<main>'
    from /Users/WREAdmin/.rvm/gems/ruby-head@global/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
    from /Users/WREAdmin/.rvm/gems/ruby-head@global/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
    from /Users/WREAdmin/.rvm/gems/ruby-head@global/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
    from /Users/WREAdmin/.rvm/gems/ruby-head@global/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
    from /Users/WREAdmin/.rvm/gems/ruby-head@global/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/railties-4.2.5.1/lib/rails/commands/server.rb:61:in `app'
    from /Users/WREAdmin/.rvm/gems/ruby-head@global/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/railties-4.2.5.1/lib/rails/commands/server.rb:139:in `log_to_stdout'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/railties-4.2.5.1/lib/rails/commands/server.rb:78:in `start'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:75:in `server'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /Users/WREAdmin/.rvm/gems/ruby-head/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

same error is shown when you attempt to generate a model with ActiveNode 

``` bash
$ rails g scaffold Model title:string lat:float lon:float
```

As per this issue:

``` bash
https://github.com/neo4jrb/neo4j/issues/1110
```

Found solution to be adding the plugin to Gemfile like so:

``` bash
gem 'neo4jrb_spatial', github: 'neo4jrb/neo4jrb_spatial', branch: 'module-definition_part2'
```

**Comment by jspenc72** [comment]
Hope this helps someone else.

**Comment by chrislgrigg** [comment]
Sorry about that, I need to block off an hour to merge that and do a proper
release. I'll comment back here when that is done.

**Comment by jspenc72** [comment]
Thank you.
